### ISSUE TITLE
Code for cyclic peptide generation

### ISSUE THREAD

**Issue by DragonDescentZerotsu** [AaronFeller/PeptideCLM#1]
Hi ! I am pretty interested in the code for cyclic peptide generation and found that the server for CycloPs is down. Is it possible to share the python 3 version of CycloPs you build? Many thanks.

**Comment by AaronFeller** [comment]
I'm working on a release for the updated version of CycloPs, it should be out in a few days.

**Comment by AaronFeller** [comment]
I just shared an in-progress repository with instructions in the readme for basic usage. I aim to build it out into a pip package in the mid-term. You can find it here: [CycloPs_v2](https://github.com/AaronFeller/CycloPs_v2).

Hope this helps!
